### ISSUE TITLE
Need link to GitHub in docs

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Ciela-Institute/caustics#231]
Use a GitHub logo as the hyperlink

**Comment by AlexandreAdam** [comment]
We can use this template apparently 

`[![GitHub Logo](https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png)](https://github.com/your-username/your-repo)
`

**Comment by mjyb16** [comment]
What's weird is that there is actually a default setting in Jupyterbook which should have been activated for this...from https://github.com/Ciela-Institute/caustics/blob/main/docs/source/_config.yml we have: 
```
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: ../../media/caustics_favicon.ico
  use_issues_button: true
  use_repository_button: true
```

I don't fully understand why it isn't working....see for example these instructions: https://jupyterbook.org/en/stable/basics/repository.html

Note that the Jupyterbook docs themselves have the button working (with all 3 options). Here is their config file, perhaps you can make sense of why ours isn't working. https://github.com/executablebooks/jupyter-book/blob/master/docs/_config.yml
